/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vn.ptit.na.ltm.baitap.client.layouts;

import java.awt.CardLayout;
import java.awt.event.ItemEvent;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import vn.ptit.na.ltm.baitap.App;
import vn.ptit.na.ltm.baitap.client.service.CommomService;
import vn.ptit.na.ltm.baitap.client.service.WorkerService;
import vn.ptit.na.ltm.baitap.entity.DistrictEntity;
import vn.ptit.na.ltm.baitap.entity.ProvinceEntity;
import vn.ptit.na.ltm.baitap.entity.WardEntity;
import vn.ptit.na.ltm.baitap.requests.SearchWorker;
import vn.ptit.na.ltm.baitap.requests.TypeLayoutEnums;
import vn.ptit.na.ltm.baitap.requests.WorkerLocationDTO;

/**
 *
 * @author Windows
 */
public class LayoutListCN extends javax.swing.JPanel implements OnLoad{

    private ProvinceEntity provinceSelect = new ProvinceEntity();
    private DistrictEntity districtSelect = new DistrictEntity();
    private WardEntity wardSelect = new WardEntity();
    private List<WorkerLocationDTO> response;

    
    public LayoutListCN() {
        initComponents();
        CommomService commomService = new CommomService();
        loading(null);
        combox_provider.addItemListener(e -> {
            if (e.getStateChange() == ItemEvent.SELECTED) {
                provinceSelect = (ProvinceEntity)e.getItem();
                commomService.setViewDistrict(combox_districts, provinceSelect);
                combox_ward.removeAllItems();
            }
        });
        
        combox_districts.addItemListener(e -> {
        if (e.getStateChange() == ItemEvent.SELECTED) {
                districtSelect = (DistrictEntity)e.getItem();
                commomService.setViewWard(combox_ward, provinceSelect, districtSelect);
            }
        });
        
        combox_ward.addItemListener(e -> {
        if (e.getStateChange() == ItemEvent.SELECTED) {
                wardSelect = (WardEntity)e.getItem();
            }
        });
        
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        jTable1.getSelectionModel().addListSelectionListener(e -> {
            if (e.getValueIsAdjusting()) return;           // bỏ qua sự kiện trung gian

            int viewRow = jTable1.getSelectedRow();          // chỉ số theo view (sau sort/filter)
            if (viewRow == -1) return;


            App app = (App) SwingUtilities.getWindowAncestor(this);
            app.changeLayout(TypeLayoutEnums.DETAIL, response.get(viewRow).getId());
        });

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jText_fullName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jText_salary = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        combo_birthStart = new javax.swing.JComboBox<>();
        combox_birthEnd = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        combox_provider = new javax.swing.JComboBox<>();
        combox_districts = new javax.swing.JComboBox<>();
        combox_ward = new javax.swing.JComboBox<>();
        btn_add = new javax.swing.JButton();
        btn_new = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();

        setAutoscrolls(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Danh sách công nhân");

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "stt", "Họ và tên", "Sinh nhật", "Quê quán", "Lương"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        jTable1.setAutoscrolls(false);
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Họ Và Tên");

        jLabel3.setText("Lương");
        jLabel3.setToolTipText("");

        jLabel4.setText("Năm sinh(từ -> đến)");

        combo_birthStart.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Không chọn", "2025", "2024", "2023", "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", "1950", "1949", "1948", "1947", "1946", "1945", "1944", "1943", "1942", "1941", "1940", "1939", "1938", "1937", "1936", "1935", "1934", "1933", "1932", "1931", "1930", "1929", "1928", "1927", "1926" }));

        combox_birthEnd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Không chọn", "2025", "2024", "2023", "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", "1950", "1949", "1948", "1947", "1946", "1945", "1944", "1943", "1942", "1941", "1940", "1939", "1938", "1937", "1936", "1935", "1934", "1933", "1932", "1931", "1930", "1929", "1928", "1927", "1926" }));

        jLabel7.setText("Tỉnh/Thành phố");

        jLabel5.setText("Quận/Huyện");

        jLabel6.setText("Xã/Phường");

        btn_add.setText("Tìm kiếm");
        btn_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_addMouseClicked(evt);
            }
        });

        btn_new.setBackground(new java.awt.Color(0, 102, 0));
        btn_new.setForeground(new java.awt.Color(255, 255, 255));
        btn_new.setText("Thêm mới");
        btn_new.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_newMouseClicked(evt);
            }
        });
        btn_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newActionPerformed(evt);
            }
        });

        btn_reset.setText("Reset");
        btn_reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_resetMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1128, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(119, 119, 119))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(combox_provider, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jText_fullName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(combox_districts, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jText_salary, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel6))
                                        .addGap(639, 639, 639))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(combo_birthStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(combox_birthEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(combox_ward, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btn_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btn_reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(46, 46, 46)
                                        .addComponent(btn_new, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(246, 246, 246))))
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(135, 135, 135)
                                .addComponent(jLabel3))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jText_fullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jText_salary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_birthStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combox_birthEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_reset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combox_provider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combox_districts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combox_ward, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_add)
                    .addComponent(btn_new))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newActionPerformed
        // Lấy JFrame bao ngoài

    }//GEN-LAST:event_btn_newActionPerformed

    private void btn_newMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_newMouseClicked
        App app = (App) SwingUtilities.getWindowAncestor(this);
        app.changeLayout(TypeLayoutEnums.ADD);
    }//GEN-LAST:event_btn_newMouseClicked

    private void btn_resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_resetMouseClicked
        this.jText_fullName.setText("");
        this.jText_salary.setText("");
        this.combox_districts.removeAllItems();
        this.combox_ward.removeAllItems();
        this.provinceSelect = new ProvinceEntity();
        this.districtSelect = new DistrictEntity();
        this.wardSelect = new WardEntity();
        combo_birthStart.setSelectedIndex(0);
        combox_birthEnd.setSelectedIndex(0);
    }//GEN-LAST:event_btn_resetMouseClicked

    private void btn_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addMouseClicked
        SearchWorker payload = new SearchWorker();
        payload.setBirthStart( getBirthDayYear(combo_birthStart.getSelectedItem().toString()));
        payload.setBirthEnd(getBirthDayYear(combox_birthEnd.getSelectedItem().toString()));
        payload.setFullName(jText_fullName.getText() != null && jText_fullName.getText().isEmpty() ? null : jText_fullName.getText());
        payload.setProvinceCode(provinceSelect.getCode());
        payload.setDistrictCode(districtSelect.getCode());
        payload.setWardCode(wardSelect.getCode());
        payload.setSalary(jText_salary.getText() == null || (jText_salary.getText().isEmpty()) ? -1L : Long.valueOf(jText_salary.getText()));
        search(payload);
       
    }//GEN-LAST:event_btn_addMouseClicked

    private Integer getBirthDayYear(String str) {
        if (str == null) return null;
        try {
           return Integer.parseInt(str);
        } catch(Exception ex) {
            return null;
        }
    }
    
    private void search(SearchWorker payload) {
        String[] columnNames = { "STT", "Họ và Tên", "Sinh Nhật", "Quê Quán", "Lương" };
        WorkerService workerService = new WorkerService();
        response = workerService.search(payload);
        int rows = response == null ? 0 : response.size();
        String [][]data = new String[rows][columnNames.length];
        for (int i = 0; i < rows; i++) {
            data[i] = new String[]{
                String.valueOf(i + 1),
                response.get(i ).getName(),
                response.get(i).getBirthday(),
                String.format("%s, %s, %s", response.get(i).getWardName(), response.get(i).getDistrictName(), response.get(i).getProvinceName()),
                String.valueOf(CommomService.fromartMonyVND(response.get(i).getSalary()))
            };
        }
        
        
        jTable1.removeAll();
        jTable1.setModel(new DefaultTableModel(data, columnNames));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_new;
    private javax.swing.JButton btn_reset;
    private javax.swing.JComboBox<String> combo_birthStart;
    private javax.swing.JComboBox<String> combox_birthEnd;
    private javax.swing.JComboBox<DistrictEntity> combox_districts;
    private javax.swing.JComboBox<ProvinceEntity> combox_provider;
    private javax.swing.JComboBox<WardEntity> combox_ward;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jText_fullName;
    private javax.swing.JTextField jText_salary;
    // End of variables declaration//GEN-END:variables

    @Override
    public <T> void loading(T input) {
        CommomService commomService = new CommomService();
        
        commomService.setViewProvince(combox_provider);
        search(new SearchWorker());
    }
}
