/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vn.ptit.na.ltm.baitap.client.layouts;

import java.awt.event.ItemEvent;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import vn.ptit.na.ltm.baitap.App;
import vn.ptit.na.ltm.baitap.client.service.CommomService;
import vn.ptit.na.ltm.baitap.client.service.WorkerService;
import vn.ptit.na.ltm.baitap.entity.DistrictEntity;
import vn.ptit.na.ltm.baitap.entity.ProvinceEntity;
import vn.ptit.na.ltm.baitap.entity.WardEntity;
import vn.ptit.na.ltm.baitap.requests.AddWorker;

/**
 *
 * @author Windows
 */
public class LayoutAdd extends javax.swing.JPanel {

    private ProvinceEntity provinceSelect;
    private DistrictEntity districtSelect;
    private WardEntity wardSelect;
    
    /**
     * Creates new form LayoutAdd
     */
    public LayoutAdd() {
        initComponents();
        
        CommomService commomService = new CommomService();
        commomService.setViewProvince(combox_provider);
        
        combox_provider.addItemListener(e -> {
            if (e.getStateChange() == ItemEvent.SELECTED) {
                provinceSelect = (ProvinceEntity)e.getItem();
                commomService.setViewDistrict(combox_districts, provinceSelect);
                combox_ward.removeAllItems();
            }
        });
        
        combox_districts.addItemListener(e -> {
        if (e.getStateChange() == ItemEvent.SELECTED) {
                districtSelect = (DistrictEntity)e.getItem();
                commomService.setViewWard(combox_ward, provinceSelect, districtSelect);
            }
        });
        
        combox_ward.addItemListener(e -> {
        if (e.getStateChange() == ItemEvent.SELECTED) {
                wardSelect = (WardEntity)e.getItem();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jText_fullName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jText_salary = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        combox_provider = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        combox_districts = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        combox_ward = new javax.swing.JComboBox<>();
        jButton_add = new javax.swing.JButton();
        jButton_close = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        jText_birthDay = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thêm mới Công nhân");

        jLabel2.setText("Họ và tên");

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jText_fullName.setToolTipText("");

        jLabel3.setText("Năm Sinh (\"dd/MM/yyyy\")");

        jLabel4.setText("Mức lương");

        jText_salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_salaryActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setPreferredSize(new java.awt.Dimension(2, 170));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );

        jLabel5.setText("Tỉnh thành/Phố");

        jLabel6.setText("Quận/Huyện");

        jLabel7.setText("Xã phường");

        combox_ward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combox_wardActionPerformed(evt);
            }
        });

        jButton_add.setBackground(new java.awt.Color(0, 153, 51));
        jButton_add.setForeground(new java.awt.Color(255, 255, 255));
        jButton_add.setText("Thêm mới");
        jButton_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_addMouseClicked(evt);
            }
        });

        jButton_close.setText("Nhập lại");
        jButton_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_closeMouseClicked(evt);
            }
        });

        btn_back.setText("Huỷ");
        btn_back.setToolTipText("");
        btn_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_backMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_back)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                        .addComponent(jButton_close, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_add, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jText_fullName)
                            .addComponent(jText_salary, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addComponent(jText_birthDay))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combox_provider, 0, 208, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(combox_districts, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7)
                            .addComponent(combox_ward, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jText_fullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jText_birthDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jText_salary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combox_provider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combox_districts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combox_ward, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_add)
                    .addComponent(jButton_close)
                    .addComponent(btn_back))
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jText_salaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_salaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_salaryActionPerformed

    private void btn_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseClicked
        App app = (App) SwingUtilities.getWindowAncestor(this);
        app.back(null);
    }//GEN-LAST:event_btn_backMouseClicked

    private void jButton_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_addMouseClicked
       String txt = CommomService.checkDate(jText_birthDay.getText());
       if (txt == null) {
           if (provinceSelect.getCode() != null && districtSelect.getCode() != null && wardSelect.getCode() != null) {
                AddWorker worker = new AddWorker();
                worker.setProvinceCode(provinceSelect.getCode());
                worker.setDistrictCode(districtSelect.getCode());
                worker.setWardCode(wardSelect.getCode());
                worker.setFullName(jText_fullName.getText());
                worker.setSalary(jText_salary.getText().isEmpty() ? 0L : Long.valueOf(jText_salary.getText()));
                worker.setBirthday(jText_birthDay.getText());
                if (new WorkerService().save(worker).equals(Boolean.FALSE)) {
                    JOptionPane.showMessageDialog( SwingUtilities.getWindowAncestor(this), "Có lỗi xẩy ra, liên hệ quản trị viên ");
                } else {
                    JOptionPane.showMessageDialog( SwingUtilities.getWindowAncestor(this), "Them moi thanh cong!");
                }
           } else {
               JOptionPane.showMessageDialog( SwingUtilities.getWindowAncestor(this), "Vui lòng chọn đầy đủ địa chỉ ");
           }
       } else {
           JOptionPane.showMessageDialog( SwingUtilities.getWindowAncestor(this), txt);
       }
    }//GEN-LAST:event_jButton_addMouseClicked

    private void jButton_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_closeMouseClicked
        jText_birthDay.setText("");
        jText_birthDay.setText("");
        jText_salary.setText("");
        combox_districts.removeAllItems();
        combox_ward.removeAllItems();
    }//GEN-LAST:event_jButton_closeMouseClicked

    private void combox_wardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combox_wardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combox_wardActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JComboBox<DistrictEntity> combox_districts;
    private javax.swing.JComboBox<ProvinceEntity> combox_provider;
    private javax.swing.JComboBox<WardEntity> combox_ward;
    private javax.swing.JButton jButton_add;
    private javax.swing.JButton jButton_close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jText_birthDay;
    private javax.swing.JTextField jText_fullName;
    private javax.swing.JTextField jText_salary;
    // End of variables declaration//GEN-END:variables
}
