/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vn.ptit.na.ltm.baitap.client.layouts;

import java.awt.event.ItemEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import vn.ptit.na.ltm.baitap.App;
import vn.ptit.na.ltm.baitap.client.service.CommomService;
import vn.ptit.na.ltm.baitap.client.service.WorkerService;
import vn.ptit.na.ltm.baitap.entity.DistrictEntity;
import vn.ptit.na.ltm.baitap.entity.ProvinceEntity;
import vn.ptit.na.ltm.baitap.entity.WardEntity;
import vn.ptit.na.ltm.baitap.requests.AddWorker;

/**
 *
 * @author Windows
 */
public class LayoutDetail extends javax.swing.JPanel implements OnLoad{

    private ProvinceEntity provinceSelect;
    private DistrictEntity districtSelect;
    private WardEntity wardSelect;
    
    private AddWorker response;
    
    /**
     * Creates new form LayoutAdd
     */
    public LayoutDetail() {
        initComponents();
        CommomService commomService = new CommomService();
        combox_provider.addItemListener(e -> {
            if (e.getStateChange() == ItemEvent.SELECTED) {
                provinceSelect = (ProvinceEntity)e.getItem();
                commomService.setViewDistrict(combox_districts, provinceSelect);
                combox_ward.removeAllItems();
            }
        });
        
        combox_districts.addItemListener(e -> {
        if (e.getStateChange() == ItemEvent.SELECTED) {
                districtSelect = (DistrictEntity)e.getItem();
                commomService.setViewWard(combox_ward, provinceSelect, districtSelect);
            }
        });
        
        combox_ward.addItemListener(e -> {
        if (e.getStateChange() == ItemEvent.SELECTED) {
                wardSelect = (WardEntity)e.getItem();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextFullName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextBirthDay = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextSalary = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        combox_provider = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        combox_districts = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        combox_ward = new javax.swing.JComboBox<>();
        jButtonUpdate = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thông tin chi tiết công nhân");

        jLabel2.setText("Họ và tên");

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTextFullName.setToolTipText("");

        jLabel3.setText("Năm Sinh");

        jLabel4.setText("Mức lương");

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setPreferredSize(new java.awt.Dimension(2, 170));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );

        jLabel5.setText("Tỉnh thành/Phố");

        jLabel6.setText("Quận/Huyện");

        jLabel7.setText("Xã phường");

        jButtonUpdate.setBackground(new java.awt.Color(0, 153, 0));
        jButtonUpdate.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUpdate.setText("Update");
        jButtonUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonUpdateMouseClicked(evt);
            }
        });

        btn_back.setText("Hủy");
        btn_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_backMouseClicked(evt);
            }
        });

        jButtonDelete.setBackground(new java.awt.Color(255, 0, 51));
        jButtonDelete.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDelete.setText("Xóa");
        jButtonDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDeleteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jTextFullName)
                                .addComponent(jTextBirthDay)
                                .addComponent(jTextSalary, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(179, 179, 179)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(combox_provider, 0, 208, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(combox_districts, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addComponent(combox_ward, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextBirthDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combox_provider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combox_districts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combox_ward, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonUpdate)
                    .addComponent(btn_back)
                    .addComponent(jButtonDelete))
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseClicked
        App app = (App) SwingUtilities.getWindowAncestor(this);
        app.back(null);
    }//GEN-LAST:event_btn_backMouseClicked

    private void jButtonUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUpdateMouseClicked
        String txt = CommomService.checkDate(jTextBirthDay.getText());
        if (txt == null) {
            WorkerService worker = new WorkerService();
            response.setProvinceCode(provinceSelect.getCode());
            response.setDistrictCode(districtSelect.getCode());
            response.setWardCode(wardSelect.getCode());
            response.setFullName(jTextFullName.getText());
            response.setSalary(jTextSalary.getText().isEmpty() ? 0L : Long.valueOf(jTextSalary.getText()));
            response.setBirthday(jTextBirthDay.getText());
        if ( worker.update(response)) {
            JOptionPane.showMessageDialog( SwingUtilities.getWindowAncestor(this), "Cap nhat thanh cong");
            App app = (App) SwingUtilities.getWindowAncestor(this);
            app.back(null);
        } else {
            JOptionPane.showMessageDialog( SwingUtilities.getWindowAncestor(this), "Cap nhat that bai");
        }
        } else {
            JOptionPane.showMessageDialog( SwingUtilities.getWindowAncestor(this), txt);
        }
        
    }//GEN-LAST:event_jButtonUpdateMouseClicked

    private void jButtonDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDeleteMouseClicked
        WorkerService worker = new WorkerService();
        if ( worker.delete( response.getId())) {
            JOptionPane.showMessageDialog( SwingUtilities.getWindowAncestor(this), "Xoa thanh cong");
            App app = (App) SwingUtilities.getWindowAncestor(this);
            app.back(null);
        } else {
            JOptionPane.showMessageDialog( SwingUtilities.getWindowAncestor(this), "Xoa that bai");
        }
    }//GEN-LAST:event_jButtonDeleteMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JComboBox<DistrictEntity> combox_districts;
    private javax.swing.JComboBox<ProvinceEntity> combox_provider;
    private javax.swing.JComboBox<WardEntity> combox_ward;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextBirthDay;
    private javax.swing.JTextField jTextFullName;
    private javax.swing.JTextField jTextSalary;
    // End of variables declaration//GEN-END:variables

    @Override
    public <T> void loading(T input) {
        WorkerService worker = new WorkerService();
        response = worker.detail((Long) input);
        
        jTextFullName.setText(response.getFullName());
        jTextSalary.setText(String.valueOf(response.getSalary()));
        jTextBirthDay.setText(response.getBirthday());
        
        CommomService commomService = new CommomService();
        commomService.setViewProvince(combox_provider);
        
        ProvinceEntity province = new ProvinceEntity();
        province.setCode(response.getProvinceCode());
        commomService.setViewDistrict(combox_districts, province);
        
        DistrictEntity district = new DistrictEntity();
        district.setCode(response.getDistrictCode());
        commomService.setViewWard(combox_ward, province, district);
        setItem(combox_provider, response.getProvinceCode());
        setItem(combox_districts, response.getDistrictCode());
        setItem(combox_ward, response.getWardCode());
    }
    
    private <T> List<T> getAllItems(JComboBox<T> cb) {
        List<T> list = new ArrayList<>();
        for (int i = 0; i < cb.getItemCount(); i++){
            list.add((T) cb.getItemAt(i));
        }
        return list;
    }
    
    
    private <T> void setItem(JComboBox<T> comboBox, String code) {
        List<T> data = getAllItems(comboBox);
        for (int i = 0; i < data.size(); i++) {
           if (data.get(i) instanceof ProvinceEntity) {
                if (((ProvinceEntity)data.get(i)).getCode().equals(code)) {
                    comboBox.setSelectedIndex(i);
                    provinceSelect = ((ProvinceEntity)data.get(i));
                    return;
                }
            } else if (data.get(i) instanceof DistrictEntity){
                if (((DistrictEntity)data.get(i)).getCode().equals(code)) {
                    comboBox.setSelectedIndex(i);
                    districtSelect = ((DistrictEntity)data.get(i));
                    return;
                }
            } else if (data.get(i) instanceof WardEntity){
                if (((WardEntity)data.get(i)).getCode().equals(code)) {
                    comboBox.setSelectedIndex(i);
                    wardSelect = ((WardEntity)data.get(i));
                    return;
                }
            } 
        }
    }
    
}
