/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vn.ptit.na.ltm.baitap;


import java.awt.CardLayout;
import java.awt.Component;
import java.io.IOException;
import java.util.Stack;
import java.util.TimeZone;
import javax.swing.JPanel;
import vn.ptit.na.ltm.baitap.client.layouts.LayoutAdd;
import vn.ptit.na.ltm.baitap.client.layouts.LayoutDetail;
import vn.ptit.na.ltm.baitap.client.layouts.LayoutListCN;
import vn.ptit.na.ltm.baitap.client.layouts.OnLoad;
import vn.ptit.na.ltm.baitap.requests.TypeLayoutEnums;

/**
 *
 * @author Windows
 */
public class App extends javax.swing.JFrame {

    private Stack<TypeLayoutEnums> backStak = new Stack<>();
    
    /**
     * Creates new form Main
     */
    public App() {
        TimeZone.setDefault(TimeZone.getTimeZone("Asia/Ho_Chi_Minh"));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRoot = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ứng dụng quản lý công nhân");
        setAlwaysOnTop(true);

        panelRoot.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout panelRootLayout = new javax.swing.GroupLayout(panelRoot);
        panelRoot.setLayout(panelRootLayout);
        panelRootLayout.setHorizontalGroup(
            panelRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelRootLayout.setVerticalGroup(
            panelRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
        );

        jLabel1.setText("BT môn lập trình mạng");

        jLabel2.setText("Trường: PTIT");

        jLabel3.setText("SV: Nguyễn Nhật Anh");

        jLabel4.setText("MSV: B22DTCNTX087-B");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(317, 317, 317)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addGap(236, 236, 236))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                App app = new App();
                app.panelRoot.setLayout(new CardLayout());
                app.panelRoot.add(new LayoutAdd(), TypeLayoutEnums.ADD.name());
                app.panelRoot.add(new LayoutDetail(), TypeLayoutEnums.DETAIL.name());
                app.panelRoot.add(new LayoutListCN(), TypeLayoutEnums.LST_WORKER.name());
                app.changeLayout(TypeLayoutEnums.LST_WORKER);
                app.setVisible(true);
            }
        });
        
    }
    
    
    public void changeLayout(TypeLayoutEnums layout) {
        ((CardLayout)this.panelRoot.getLayout()).show(this.panelRoot, layout.name());
        backStak.add(layout);
    }
    
    public <T>void changeLayout(TypeLayoutEnums layout, T data) {
        ((CardLayout)this.panelRoot.getLayout()).show(this.panelRoot, layout.name());
        backStak.add(layout);
        JPanel panel = getCurrentPanel();
        if (panel != null && panel instanceof OnLoad) {
            ((OnLoad)panel).loading(data);
        }
    }
   
    public <T> void back(T data) {
        if (!backStak.isEmpty()) {
            backStak.pop();
            ((CardLayout)this.panelRoot.getLayout()).show(this.panelRoot, backStak.peek().name());
            JPanel panel = getCurrentPanel();
            if (panel != null && panel instanceof OnLoad) {
                ((OnLoad)panel).loading(data);
            }
        }
    }
    
    public JPanel getCurrentPanel() {
        for (Component c : panelRoot.getComponents()) {
            if (c.isVisible() && c instanceof JPanel) {
                return (JPanel) c;          // với CardLayout chỉ 1 card visible
            }
        }
        return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JPanel panelRoot;
    // End of variables declaration//GEN-END:variables
}
